#!/bin/bash
echo "--- 02_CREATE_APPCONF_PACKAGE START"
echo "### ENVIRONMENT ###"
env | grep AWS | sort
echo "### ENVIRONMENT ###"
TIC=`date "+%s"`

# /home/cloudcat/.12345
FAKE_HOME="/home/cloudcat/.$AWS_PID"
export HOME=$FAKE_HOME

# /home/cloudcat/.12345/fusion
FUSION="$FAKE_HOME/fusion"
echo "FUSION is now '$FUSION'"

cd $FUSION
export PERL5LIB=/data/perl5/lib/perl5:$FUSION/lib

# Run create appconf package
CMD="./utils/release --git-branch=master --skip-checkout --create-appconf-package --machine=$AWS_HOSTS --aws-project=$AWS_ENVNAME"
echo "ABOUT TO RUN [ $CMD ]"
`$CMD >.output 2>&1 >>.output`
STATUS=$?
OUTPUT=`cat .output`
echo "OUTPUT [ $OUTPUT ]"
echo "STATUS [ $STATUS ]"

TOC=`date "+%s"`
ELAPSED=$(( $TOC - $TIC ))
TOTAL=$(( $TOC - $AWS_START ))
echo ">>> TOOK $ELAPSED SECONDS [ $TOTAL SECONDS TOTAL ]"
echo "--- 02_CREATE_APPCONF_PACKAGE FINISH"
exit $STATUS
