#!/bin/bash
echo "--- 03_CHECK_NFS_MOUNTS START"
echo "### ENVIRONMENT ###"
env | grep AWS | sort
echo "### ENVIRONMENT ###"
TIC=`date "+%s"`

CHECK_NFS_MOUNTS="/bin/mount -t nfs"
HOME='/home/cloudcat'
SLEEP=15
STATUS=0

# Internal Field Separator
# http://stackoverflow.com/a/7718539/1799189
IFS=','

TOTAL_STATUS=0
for HOST in $AWS_HOSTS; do

    HOST_TYPE=`echo $HOST | perl -pe 's|\d+||;'`
    echo "CHECKING NFS MOUNTS [ $HOST ]"
    echo "ABOUT TO RUN [ ssh -oStrictHostKeyChecking=no $HOST.$AWS_ENVNAME -T '$CHECK_NFS_MOUNTS' ]"
    MOUNTS=`ssh -oStrictHostKeyChecking=no $HOST.$AWS_ENVNAME -T $CHECK_NFS_MOUNTS`
    STATUS=$?
    if [[ $STATUS -ne "0" ]]; then
        echo "Host '$HOST' NOT OK!"
    else
        echo $MOUNTS
        if [[ $HOST_TYPE == web* || $HOST_TYPE == exp* ]]; then
            if  echo $MOUNTS | grep -q ':/cdb on /cdb'                      &&
                echo $MOUNTS | grep -q ':/cmweb on /cmweb'                  &&
                echo $MOUNTS | grep -q ':/cmwrite on /cmwrite'              &&
                echo $MOUNTS | grep -q ':/n1 on /cm/node1'                  &&
                echo $MOUNTS | grep -q ':/z2/archive01 on /stats/archive01' &&
                echo $MOUNTS | grep -q ':/z2 on /stats'; then
                echo "==> SUCCESS"
            else
                echo "==> FAILURE"
                TOTAL_STATUS=$(( $TOTAL_STATUS + 1 ))
            fi
        else
            echo "==> SKIP (no mount checks defined)"
        fi
    fi
    TOTAL_STATUS=$(( $TOTAL_STATUS + $STATUS ))
done

TOC=`date "+%s"`
ELAPSED=$(( $TOC - $TIC ))
TOTAL=$(( $TOC - $AWS_START ))
echo ">>> TOOK $ELAPSED SECONDS [ $TOTAL SECONDS TOTAL ]"
echo "--- 03_CHECK_NFS_MOUNTS FINISH"
exit $TOTAL_STATUS
