#!/usr/bin/env perl

use warnings;
use strict;

my ($aws_env, $hostnames, @commands) = @ARGV;
chomp(my $git_top_level = `git rev-parse --show-toplevel`);
$aws_env and $hostnames and scalar @commands
    or die "usage: run_command devXX web01,web02 ls -f1\n";

my $command = "'" . join(' ', @commands) . "'";
my $cmd = "$git_top_level/scripts/run_command_for_env_hosts $aws_env $hostnames $command";

my $results = `$cmd`;

print $results;

exit 0;
