#!/bin/bash
echo "--- 10_CREATE_EXP_SECRETS_HOSTS_PACKAGE START"
echo "### ENVIRONMENT ###"
env | grep AWS | sort
echo "### ENVIRONMENT ###"
TIC=`date "+%s"`

STATUS=0

FAKE_HOME="/home/cloudcat/.$AWS_PID"
FAKE_OUT="$FAKE_HOME/.output"
export HOME=$FAKE_HOME

FUSION="$FAKE_HOME/fusion"
echo "cd $FUSION"

cd $FUSION

rm -f secrets.conf
touch secrets.conf

# TODO: Do ebm_pub and ebm_priv both get secrets?
POSSIBLE_SECRETS_HOSTS="bbx,ebm,exp,load,web,api,sub"
REGEX="^([a-z]+)"
IFS=','
for HOST in $AWS_HOSTS; do
    # web01 => web
    [[ $HOST =~ $REGEX ]]
    NAME="${BASH_REMATCH[1]}"

    # if name is in the list of possible secret hosts
    if [[ $POSSIBLE_SECRETS_HOSTS == *"$NAME"* ]]; then
        echo "$HOST.$AWS_ENVNAME" >> secrets.conf
    fi
done
echo "SECRETS HOSTS:"
cat secrets.conf

SHA1=`git log -1 --format="%H" | cut -b-10`
echo "SHA1 [ $SHA1 ]"
/data/cheetah/cloudControl/aws/scripts/package_for_file --file=secrets.conf --dest=/data/cheetah/etc --name=ctah-secrets-hosts-$AWS_ENVNAME-$AWS_START.$SHA1
STATUS=$?
echo "STATUS [ $STATUS ]"

TOC=`date "+%s"`
ELAPSED=$(( $TOC - $TIC ))
TOTAL=$(( $TOC - $AWS_START ))
echo ">>> TOOK $ELAPSED SECONDS [ $TOTAL SECONDS TOTAL ]"
echo "--- 10_CREATE_EXP_SECRETS_HOSTS_PACKAGE FINISH"
exit $STATUS
